IF /I "%PROCESSOR_ARCHITECTURE%"=="x32" (
    IF NOT DEFINED PROCESSOR_ARCHITEW6432 (
        SET ARCH=32
    ) ELSE (
        SET ARCH=64
    )
) ELSE IF /I "%PROCESSOR_ARCHITECTURE%"=="x86" (
    IF NOT DEFINED PROCESSOR_ARCHITEW6432 (
        SET ARCH=32
    ) ELSE (
        SET ARCH=64
    )
) ELSE (
    SET ARCH=64
)

SET PATH=%CD%\utilities;%PATH%
SET SEVENZAEXE=%CD%\utilities\7za%ARCH%.exe
SET START=%CD%

SET USEGIT=1
IF /I "%1"=="/nogit" SET USEGIT=0

IF /I "%1"=="/NOVERSION" ( 
	SET OUTDIR=%START%\debug
	SET USEVERSION=0
) ELSE ( 
	IF %USEGIT%==1 (
		SET OUTDIR=%START%\release_beta
	) ELSE (
		SET OUTDIR=%START%\release
	)
	SET USEVERSION=1	
)

IF NOT EXIST "%OUTDIR%" MKDIR "%OUTDIR%"
