// Jumpmaze Forced Restart
// Made by Wirtualnosc
#library "invclear"
#include "zcommon.acs"

script 899 ENTER
{
	if (!(GetLevelInfo(LEVELINFO_LEVELNUM)>=33 && GetLevelInfo(LEVELINFO_LEVELNUM)<=64) && StrCmp(StrParam(n:PRINTNAME_LEVEL),"DRAG")) {
		SetActorProperty(0,APROP_Health,100);
		SetActorProperty(0,APROP_Invulnerable,0);
		SetActorProperty(0,APROP_NoTarget,0);
		ClearInventory();
		Delay(1);
		GiveInventory("Fist",1);
		GiveInventory("Pistol",1);
	}
}